# Setup
title: "だろうに"
description: "My record keeping for technology, life, and much more."
url: https://zujiancai.github.io
avatar: /assets/img/avatar.jpg
paginate: 8
permalink: pretty
cover_image: /assets/img/bg-christmas.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
  - vendor

# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: Zujian Cai
  links:
    - https://github.com/zujiancai
google_site_verification: xxxxx
lang: zh

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
disqus: zujiancai

# Specify the author for blog posts
author:
  name: Zujian Cai
  url: https://github.com/zujiancai
  email: zujiancai@yahoo.com
